version: '3'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - WEBGOAT_PORT=8080
      - WEBGOAT_SSLENABLED=false
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
    ports:
      - "8080:8080"
      - "9001:9001"
    volumes:
      - .:/home/webgoat/.webgoat
    command: --server.address=0.0.0.0
  webwolf:
    image: webgoat/webwolf
    ports:
      - "9090:9090"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
