apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      app: webgoat
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: webgoat
        tier: frontend
        track: stable
    spec:
      containers:
      - image: us.icr.io/zubcevic/reverseproxy
        name: reverseproxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}


