apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f goatcloud.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reverseproxy
    spec:
      containers:
      - image: us.icr.io/zubcevic/reverseproxy
        name: reverseproxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
