apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f goatcloud.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webgoat
  name: webgoat
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: webgoat
status:
  loadBalancer: {}
