apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  selector:
    matchLabels:
      app: webgoat
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: webgoat
        tier: backend
        track: stable
    spec:
      containers:
      - args:
        - --server.address=0.0.0.0
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: WEBGOAT_PORT
          value: "8080"
        - name: WEBGOAT_SSLENABLED
          value: "false"
        - name: WEBWOLF_HOST
          value: webwolf
        - name: WEBWOLF_PORT
          value: "9090"
        image: us.icr.io/zubcevic/webgoat-8.0
        name: webgoat
        resources: {}
        workingDir: /home/webgoat
      restartPolicy: Always
status: {}
